# Generated by Django 4.2.5 on 2023-10-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drink',
            options={'ordering': ['name']},
        ),
    ]
